version: '3.8'
services:
  hello-algo-code:
    build:
      context: .
      args:
        LANGS: ${LANGS_SDK}
    image: hello-algo-code
    container_name: hello-algo-code
    stdin_open: true
    tty: true
