name: Kotlin
on: 
  push:
    branches: [ "main" ]
    paths: ["codes/kotlin/**/*.kt"]
  pull_request:
    branches: [ "main" ]
    paths: ["codes/kotlin/**/*.kt"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      os: [ ubuntu-20.04, macos-latest, windows-latest ]
    steps: 
      - uses: actions/checkout@v4.1.2
      - uses: fwilhe2/setup-kotlin@main
        with:
          install-native: true
          version: "1.9.20"
      - run: kotlinc codes/kotlin/**/*.kt -include-runtime -d codes/kotlin/build/test.jar; java -jar codes/kotlin/build/test.jar
