name: Kotlin
on:
  push:
    branches: ["main"]
    paths: ["codes/kotlin/**/*.kt"]
  pull_request:
    branches: ["main"]
    paths: ["codes/kotlin/**/*.kt"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
        - uses: actions/checkout@v4.1.2
        - run: kotlinc codes/kotlin/**/*.kt -include-runtime -d codes/kotlin/build/test.jar
